### ISSUE TITLE
Spelfout in waardelijst 

### ISSUE THREAD

**Issue by pmaria** [Kadaster/TOP10NL#2]
In de uitbreiding van de waardelijst T10FunctioneelGebiedTypeFunctioneelGebied.csv zit een spelfout bij code 79: `visvijvercpomplex`.

https://github.com/kadaster/top10nl/blob/master/waardelijst/20190201/T10FunctioneelGebiedTypeFunctioneelGebied.csv#L62

Komt deze code daadwerkelijk op deze manier voor in de data? Of is dit alleen een foutje in de waardelijst?

**Comment by pmaria** [comment]
Hetzelfde geldt voor code 74: `gebied voor readioastronomie`

https://github.com/kadaster/top10nl/blob/master/waardelijst/20190201/T10FunctioneelGebiedTypeFunctioneelGebied.csv#L20

**Comment by DanielteWinkel** [comment]
Bedankt voor het doorgeven, ik heb de fouten hersteld.
